library(SuperLearner)

#' Fit a MultiGPS Estimator for a Specific Target Treatment Value
#'
#' @param x_eval A numeric vector of length p representing the target treatment value.
#' @param X A numeric matrix (n x p) of observed continuous treatments.
#' @param C A numeric matrix (n x q) of observed confounders.
#' @param mu_fitter A custom function(W, C) that trains a model and returns a fitted object. Response is scalar.
#' @param h1 An optional numeric vector of length p for the bandwidths. Defaults to NULL.
#' @param c_multiplier A numeric scalar for the rule-of-thumb bandwidth calculation. Defaults to 1.25.
#' @return An S3 object of class "multigps".

multigps <- function(x_eval, X, C, mu_fitter, h1 = NULL, c_multiplier = 1.25) {
  n <- nrow(X)
  p <- ncol(X)
  
  # 1. Bandwidth Selection
  # If h1 is not provided, calculate the rule of thumb for each treatment dimension
  if (is.null(h1)) {
    treatment_sds <- apply(X, 2, sd)
    h1 <- c_multiplier * treatment_sds * (n^(-0.2))
  }
  
  # Ensure h1 is the correct length just in case the user provided a scalar manually
  if (length(h1) == 1 && p > 1) {
    h1 <- rep(h1, p)
  }
  
  # 2. Compute the pseudo-outcome W_i for all observations
  W <- rep(1, n)
  for (j in 1:p) {
    u <- (X[, j] - x_eval[j]) / h1[j]
    W <- W * dnorm(u) 
  }
  
  # 3. Fit the outcome regression using the user-supplied ML wrapper
  inner_fit <- mu_fitter(W, C)
  
  # 4. Store the components needed to predict on NEW confounders later
  res <- list(
    inner_fit = inner_fit,
    x_eval = x_eval,
    h1 = h1,
    p = p
  )
  
  class(res) <- "multigps"
  return(res)
}

#' Predict Method for MultiGPS Objects with Flooring
#'
#' @param object An object of class "multigps".
#' @param newdata A numeric matrix or data frame of NEW confounders (C_new).
#' @param delta_n A small positive numeric threshold to floor the density estimates. Defaults to 1e-4.
#' @param ... Additional arguments passed to the underlying ML predict method.
#' @return A numeric vector of estimated conditional densities f(x_eval | newdata).

predict.multigps <- function(object, newdata, delta_n = 1e-4, ...) {
  # 1. Generate mu_hat by predicting from the inner fitted model
  if(class(object$inner_fit) == "SuperLearner"){
    mu_hat <- predict(object$inner_fit, newdata = newdata, ...)$pred
  } else{
    mu_hat <- predict(object$inner_fit, newdata = newdata, ...)
  }
  mu_hat <- as.numeric(mu_hat)
  
  # 2. Scale by the product of the bandwidths to get the raw density
  bandwidth_product <- prod(object$h1)
  raw_f_hat <- mu_hat / bandwidth_product
  
  # 3. Apply the trimming/flooring check to prevent negative or tiny estimates
  # pmax compares each element to delta_n and returns the maximum
  f_hat_safe <- pmax(raw_f_hat, delta_n)
  
  return(f_hat_safe)
}

#' SuperLearner Fitter for MultiGPS
#'
#' @param W Numeric vector. The continuous pseudo-outcome generated by the kernel.
#' @param C Matrix or data frame of confounders.
#' @param ... Additional arguments passed directly to SuperLearner::SuperLearner 
#' @return A fitted SuperLearner object.

SL_fitter <- function(W, C, ...) {
  # SuperLearner strictly requires X to be a data.frame
  C_df <- as.data.frame(C)
  
  # Since the pseudo-outcome W is continuous, we default to family = gaussian()
  fit <- SuperLearner::SuperLearner(
    Y = W, 
    X = C_df, 
    family = gaussian(), 
    ...
  )
  
  return(fit)
}
